name: InfuseRevampS2
version: '1.0'
main: dijon.infuseRevampS2.InfuseRevampS2
api-version: '1.21'
commands:
  infusegive:
    usage: /infusegive
  ldrain:
    usage: /ldrain
  rdrain:
    usage: /rdrain
  lspark:
    usage: /lspark
  rspark:
    usage: /rspark
  setduration:
    usage: /setduration
  setcooldown:
    usage: /setcooldown
  swap:
    usage: /swap
  trust:
    usage: /trust
  trusted:
    usage: /trusted